rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # HTTP GET 2xx
  - job_name: blackbox_http
    scrape_interval: 10s
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/http/*.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # ICMP ping
  - job_name: blackbox_icmp
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/icmp/*.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # TCP connect
  - job_name: blackbox_tcp
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [tcp_connect]
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/tcp/*.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # gRPC TLS
  - job_name: blackbox_grpc
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [grpc]
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/grpc/*.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # PostgreSQL SSL check
  - job_name: blackbox_postgresql
    scrape_interval: 60s
    metrics_path: /probe
    params:
      module: [postgresql]
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/postgresql/*.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
